#!/usr/bin/python
import json
import sys
import os.path

pd = os.path.dirname

this_dir = pd(os.path.abspath(__file__))

sys.path.append( pd(this_dir) )
sys.path.append( os.path.join(pd(pd(this_dir)), 'paxos') )

from zpax import keyval


from twisted.internet import reactor, defer


ids = dict( a = 1, b = 2, c = 3 )
#ids = dict( a = 1, b = 2 )

snode = None

nodes = list()

for i in ids.itervalues():
    pax_rep = 'tcp://127.0.0.1:222{}'.format(i)
    pax_pub = 'tcp://127.0.0.1:333{}'.format(i)
    nodes.append( dict(uid=pax_pub, pub_addr=pax_pub, rep_addr=pax_rep) )

cfg = dict( nodes=nodes )


def doit():
    global snode
    
    i = sys.argv[1]
    lcl_pax_rep = 'tcp://127.0.0.1:222{}'.format(ids[i])
    lcl_pax_pub = 'tcp://127.0.0.1:333{}'.format(ids[i])
    lcl_rep     = 'tcp://127.0.0.1:444{}'.format(ids[i])
    del ids[i]
    pax_pubs = [ 'tcp://127.0.0.1:333{}'.format(x) for x in ids.values() ]
    reps     = [ 'tcp://127.0.0.1:444{}'.format(x) for x in ids.values() ]

    snode = keyval.KeyValueDB( lcl_pax_pub, lcl_rep, reps,
                               '/tmp', ':memory:' )

    snode.initialize( json.dumps(cfg) )
    #snode.connect( pax_pubs )
            
reactor.callWhenRunning(doit)
reactor.run()


