#!/usr/bin/python

import sys
import os.path

pd = os.path.dirname

this_dir = pd(os.path.abspath(__file__))

sys.path.append( pd(this_dir) )
sys.path.append( os.path.join(pd(pd(this_dir)), 'paxos') )

from zpax import single_value, net


from twisted.internet import reactor, defer


ids = dict( a = 1, b = 2, c = 3 )

snode = None


class SVN(single_value.SingleValueNode):
    hb_period       = 0.1
    liveness_window = 1


def doit():
    global snode

    znodes = dict()

    for n, i in ids.iteritems():
        znodes[n] = ('tcp://127.0.0.1:222{}'.format(i),
                     'tcp://127.0.0.1:333{}'.format(i))

    i = ids[ sys.argv[1] ]    
    n = net.NetworkNode( sys.argv[1] )
    
    n.connect(znodes, False)
    
    snode = SVN( n, 2,
                 'tcp://127.0.0.1:444{}'.format(i),
                 'tcp://127.0.0.1:555{}'.format(i) )


        
reactor.callWhenRunning(doit)
reactor.run()


