#!/usr/bin/python

import sys
import os.path

pd = os.path.dirname

this_dir = pd(os.path.abspath(__file__))

sys.path.append( pd(this_dir) )
sys.path.append( os.path.join(pd(pd(this_dir)), 'paxos') )

from twisted.internet import reactor, defer

from zpax import tzmq

def tz():

    def doit():
        s = tzmq.ZmqReqSocket()
    
        def on_recv(parts):
            print 'Received: ', parts
            reactor.stop()
        
        #s.connect('tcp://127.0.0.1:3331')
        s.messageReceived = on_recv
        
        print 'Sending...'

        s.send('hello world!')

        def cb():
            print 'Connecting!'
            s.connect('tcp://127.0.0.1:3331')
            
        reactor.callLater(3, cb)

        
    reactor.callWhenRunning(doit)
    reactor.run()

tz()
