#!/usr/bin/python

import zmq
import random

from twisted.internet import reactor, defer

from zpax import tzmq

def straight():
    ctx = zmq.Context()
    s = ctx.socket(zmq.PUB)

    s.bind('tcp://*:5556')
    c = 0
    while True:
        c += 1
        s.send('foo ' + str(c))

def straight2():
    ctx = zmq.Context()
    s = ctx.socket(zmq.REP)

    s.bind('tcp://*:5556')
    c = 0
    while True:
        c += 1
        print 'Recv: ', s.recv_multipart()
        s.send('foo ' + str(c))

        
def tz():


    def doit():
        s = tzmq.ZmqPubSocket()

        s.bind('tcp://*:5556')
        
        o = type('foo', (object,), {})()
        o.count = 0

        def send():
            o.count += 1
            print 'Sending: ', o.count
            s.send('foo {}'.format(o.count), 'part2', str(o.count))
            reactor.callLater(0.1,send)

        send()

    reactor.callWhenRunning(doit)
    reactor.run()


def tz2():


    def doit():
        s = tzmq.ZmqRepSocket()

        o = type('foo', (object,), {})()
        o.count = 0
        
        def onreq( req ):
            o.count += 1
            print 'Req {}: Sending: {}'.format(req, o.count)
            s.send('foobar ' + str(o.count))

        s.messageReceived = onreq
            
        s.bind('tcp://*:5556')
        
        

    reactor.callWhenRunning(doit)
    reactor.run()

#straight2()
tz2()
